# Configuración de pytest

[pytest]
# Busca solo en la carpeta tests
testpaths = tests

# Solo archivos que empiecen con test_ y terminen con .py
python_files = test_participant

# Solo clases que empiecen con Test
python_classes = Test*

# Solo funciones que empiecen con test_
python_functions = test_*

# -v: verbose, --cov: medir cobertura, term-missing: mostrar líneas no cubiertas
addopts = -v --cov=app --cov-report=term-missing