[pytest]
testpaths = tests  # Busca solo en la parte test 
python_files = test_participant # Solo archivos que empiecen con test_ y terminen con .py 
python_classes = Test*
python_functions = test_* # lo mismo para estas dos (clases y funciones)
addopts = -v --cov=app --cov-report=term-missing 

# cov es para medir la cobertura
# cov-report es para mostrar un reporte de cobertura INCLUYENDO las lineas no cubiertas (term-missing)