apiVersion: v1
kind: Service
metadata:
  name: podcast-api-service
  namespace: podcast-api

spec:
  selector:
    app: podcast-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: LoadBalancer